import { Chip, Stack, Typography } from "@mui/material";
import SectionCard from "../../../Common/SectionCard";
import InfoRow from "../../../Common/InfoRow";
import { AI_FLAG_COLORS } from "./statusColors";

function Text({ value }) {
  return value ? (
    <Typography sx={{ whiteSpace: "pre-wrap", overflowWrap: "anywhere" }}>{value}</Typography>
  ) : (
    <Typography color="text.secondary">Not generated yet</Typography>
  );
}

// Read-only: these fields are written by the AI, not by people.
function AiSection({ record }) {
  return (
    <SectionCard title="AI check-in review">
      <Stack spacing={1}>
        <Typography variant="caption" color="text.secondary">
          Generated by AI. Check it against the updates before acting on it.
        </Typography>

        <InfoRow
          label="Concern flag"
          labelWidth={190}
          value={
            record.aiConcernFlag ? (
              <Chip label={record.aiConcernFlag} size="small" color={AI_FLAG_COLORS[record.aiConcernFlag] ?? "default"} />
            ) : (
              <Typography color="text.secondary">Not generated yet</Typography>
            )
          }
        />
        <InfoRow label="Check-in summary" labelWidth={190} value={<Text value={record.aiCheckInSummary} />} />
        <InfoRow label="Suggested next action" labelWidth={190} value={<Text value={record.suggestedNextAction} />} />
      </Stack>
    </SectionCard>
  );
}

export default AiSection;
