// One-off: seeds the review_items punch-list (server/reviewItems/,
// src/pages/ReviewItems) with the gaps found in the 2026-10-05 app-vs-brief
// gap analysis (IBKT_System_V1_22.04.26.pptx vs the current codebase).
// Safe to re-run: an item with the same title is left alone, not duplicated.
//
//   node scripts/seedGapAnalysisItems.js
import "dotenv/config";
import { query, closeDatabase } from "../database/db.js";
import { createReviewItem } from "../reviewItems/store.js";

const ITEMS = [
  {
    category: "internal",
    title: "No Rescuer onboarding UI/route exists",
    detail:
      "The Rescuers board has columns for vet permissions, legal/financial agreements, media usage permission and medical disclosure, but there is no page, route, or form anywhere that sets them. Entry is still manual/WhatsApp-only.",
  },
  {
    category: "internal",
    title: "WhatsApp is not replaced by anything",
    detail:
      "No WhatsApp/Twilio/SMS API integration exists in the codebase. The Rescuers board still has a WHATSAPP_NUMBER field and preferred-contact-method setting, implying WhatsApp is assumed as a live channel rather than replaced.",
  },
  {
    category: "internal",
    title: "AI review is fully wired but not connected to a real AI provider",
    detail:
      "server/aiReview/ implements the full draft-review flow (summary, concerns, missing info, suggested questions, risk score) end to end, but provider.js only registers a 'mock' provider. No OpenAI/Anthropic key or call exists anywhere. This is the closest gap to done - needs an API key and a real provider implementation, not a rebuild.",
  },
  {
    category: "internal",
    title: "No payment processor integration",
    detail:
      "Payments are tracked (PAYMENT_STATUS/PAYMENT_DATE/PAYMENT_REQUIRED) but marked by hand - code comment in PaymentsTab.jsx notes this explicitly. No Stripe/PayPal/checkout code exists anywhere.",
  },
  {
    category: "internal",
    title: "No sensitive-field visibility control (e.g. microchip number)",
    detail:
      "Microchip number is a plain visible text field to anyone who can open a cat record. No field-level masking/redaction mechanism exists in the codebase.",
  },
  {
    category: "internal",
    title: "Testimonial requests not implemented",
    detail:
      "Zero references to 'testimonial' anywhere in src/ or server/. Part of the post-adoption flow in the brief that hasn't been built.",
  },
  {
    category: "internal",
    title: "No cap on post-adoption chase attempts",
    detail:
      "chaseCount increments when a check-in is marked Sent, but nothing stops chasing after a defined number of attempts, as the brief calls for.",
  },
  {
    category: "internal",
    title: "Cat listing isn't gated on required fields being complete",
    detail:
      "PROFILE_COMPLETE and MEDIA_COMPLETE boolean columns exist on the Cats board, but nothing reads or enforces them before a cat's status moves to Adoption Ready.",
  },
  {
    category: "internal",
    title: "No 3-month update nudge for unadopted cats",
    detail:
      "UPDATE_REQUESTED is a manual flag on the Cats board - no scheduler sets or reads it to trigger a reminder after 3 months unadopted.",
  },
  {
    category: "internal",
    title: "No adopter/rescuer self-service travel submission",
    detail:
      "Travel data is staff-entered only, via a tab inside the Cat/Active Application workspaces. The brief calls for both the adopter and the rescuer to be able to submit logistics data themselves; no such portal/route exists.",
  },
  {
    category: "internal",
    title: "Contracts are tracked but not generated by the app",
    detail:
      "Draft/final/signed contract status is tracked (contracts.js, contractDocumentTypes.js), but the actual documents are drafted and signed externally via Jotform, then matched back to a cat by microchip number. The app doesn't generate contracts itself.",
  },
  {
    category: "internal",
    title: "Post-adoption reminders are not actually automated",
    detail:
      "The check-in schedule (24h/72h/weekly/3mo/6mo/yearly) matches the brief closely, but nothing sends anything automatically - a staff member has to manually mark each check-in as sent. No cron/scheduled job contacts adopters on any cadence.",
  },
  {
    category: "internal",
    title: "Board visibility rules don't match the brief, and some permission checks are unused",
    detail:
      "The brief asks for Travel and Post-Adoption to be admin-only, but canViewTravel/canViewPostAdoption also grant Volunteers (and Adopters, for post-adoption) access. Several of these permission helpers are defined but never referenced anywhere in the codebase, so even the partial rules may not be enforced.",
  },
  {
    category: "internal",
    title: "System is still mid-migration, not yet a single source of truth",
    detail:
      "Monday.com remains the source of truth for most boards, with a Postgres mirror being cut over board by board. Cat/foster intake still partly flows through Jotform rather than being captured natively in the app.",
  },
  {
    category: "internal",
    title: "No distinct crate weight field on Travel",
    detail:
      "The brief asks for crate size + weight. Only CRATE_SIZE (a dropdown) exists on the Travel board - no weight field was found. Needs confirming - may be intentionally out of scope.",
  },
  {
    category: "internal",
    title: "No obvious travel date field",
    detail:
      "The brief calls for a travel date per case. Only flight number and departure/arrival airports were found on the Travel board - no dedicated date field. Needs confirming - may exist under another name.",
  },
];

for (const item of ITEMS) {
  const { rows } = await query("select 1 from review_items where title = $1", [item.title]);

  if (rows.length > 0) {
    console.log(`Already there: ${item.title}`);
    continue;
  }

  await createReviewItem(item);
  console.log(`Added: ${item.title}`);
}

await closeDatabase();
process.exit(0);
